-- MySQL Script generated by MySQL Workbench
-- Fri Jan  6 02:20:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema serwis_ogloszeniowy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `serwis_ogloszeniowy` DEFAULT CHARACTER SET utf8mb3 ;
USE `serwis_ogloszeniowy` ;

-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`authorities` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `authority` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `enabled` TINYINT(1) NOT NULL,
  `reset_code` VARCHAR(70) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_idx` (`username` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`block_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`block_list` (
  `block_id` INT NOT NULL AUTO_INCREMENT,
  `blocking_user_id` INT NOT NULL,
  `blocked_user_id` INT NOT NULL,
  PRIMARY KEY (`block_id`),
  INDEX `blocking_user_id_idx` (`blocking_user_id` ASC) ,
  CONSTRAINT `blocking_user_id`
    FOREIGN KEY (`blocking_user_id`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`messages` (
  `message_id` INT NOT NULL AUTO_INCREMENT,
  `sender_id` INT NOT NULL,
  `receiver_id` INT NOT NULL,
  `message_date` DATETIME NOT NULL,
  `message_content` LONGTEXT NOT NULL,
  PRIMARY KEY (`message_id`),
  INDEX `sender_id_idx` (`sender_id` ASC) ,
  INDEX `sender_receiver_idx` (`sender_id` ASC, `receiver_id` ASC) ,
  CONSTRAINT `sender_id`
    FOREIGN KEY (`sender_id`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`offers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`offers` (
  `offer_id` INT NOT NULL AUTO_INCREMENT,
  `date_of_creation` DATETIME NOT NULL,
  `description` LONGTEXT NOT NULL,
  `is_active` TINYINT(1) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `user_fk` INT NOT NULL,
  PRIMARY KEY (`offer_id`),
  INDEX `user_fk_idx` (`user_fk` ASC) ,
  CONSTRAINT `user_fk`
    FOREIGN KEY (`user_fk`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`offer_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`offer_report` (
  `id_offer_report` INT NOT NULL AUTO_INCREMENT,
  `offer_report_desc` LONGTEXT NOT NULL,
  `reported_offer_id` INT NOT NULL,
  PRIMARY KEY (`id_offer_report`),
  INDEX `reported_offer_id_idx` (`reported_offer_id` ASC) ,
  CONSTRAINT `reported_offer_id`
    FOREIGN KEY (`reported_offer_id`)
    REFERENCES `serwis_ogloszeniowy`.`offers` (`offer_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`subscriptions` (
  `sub_id` INT NOT NULL AUTO_INCREMENT,
  `subbed_offer_id` INT NOT NULL,
  `subbing_user_id` INT NOT NULL,
  `date_of_sub` DATE NOT NULL,
  PRIMARY KEY (`sub_id`),
  INDEX `subbed_offer_id_idx` (`subbed_offer_id` ASC) ,
  INDEX `subbing_user_id_idx` (`subbing_user_id` ASC) ,
  CONSTRAINT `subbed_offer_id`
    FOREIGN KEY (`subbed_offer_id`)
    REFERENCES `serwis_ogloszeniowy`.`offers` (`offer_id`),
  CONSTRAINT `subbing_user_id`
    FOREIGN KEY (`subbing_user_id`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`user_auth`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`user_auth` (
  `user_id_auth` INT NOT NULL,
  `role_id_auth` INT NOT NULL,
  INDEX `user_id_auth_idx` (`user_id_auth` ASC) ,
  INDEX `role_id_auth_idx` (`role_id_auth` ASC) ,
  CONSTRAINT `role_id_auth`
    FOREIGN KEY (`role_id_auth`)
    REFERENCES `serwis_ogloszeniowy`.`authorities` (`role_id`),
  CONSTRAINT `user_id_auth`
    FOREIGN KEY (`user_id_auth`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`user_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`user_details` (
  `user_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `last_login` DATETIME NOT NULL,
  INDEX `user_id_idx` (`user_id` ASC) ,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `serwis_ogloszeniowy`.`user_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `serwis_ogloszeniowy`.`user_report` (
  `report_id` INT NOT NULL AUTO_INCREMENT,
  `user_report_desc` LONGTEXT NOT NULL,
  `reported_user_id` INT NOT NULL,
  `reporting_user_id` INT NOT NULL,
  PRIMARY KEY (`report_id`),
  INDEX `reported_user_id_idx` (`reported_user_id` ASC) ,
  CONSTRAINT `reported_user_id`
    FOREIGN KEY (`reported_user_id`)
    REFERENCES `serwis_ogloszeniowy`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
